-- Prueba transaccional: no conserva usuarios, mediciones ni tareas de prueba.
begin;
do $$
declare u uuid; o bigint; i bigint; r bigint; next_r bigint; c bigint; a bigint; t1 bigint; t2 bigint; newer bigint; blocked boolean;
begin
 select id into strict u from auth.users order by created_at limit 1;
 insert into role_assignments(email,role) values ('corrective-gcg@example.invalid','gcg');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-manager@example.invalid','role','authenticated')::text,true);
 insert into objectives(name,category,owner_email,target_date) values ('Prueba reversible correctivas','Operaciones','corrective-manager@example.invalid','2030-12-31') returning id into o;
 insert into indicators(objective_id,name,target,unit,comparator,frequency,approval_status) values(o,'Prueba reversible',90,'%', '>=','Mensual','Aprobado') returning id into i;
 insert into indicator_reports(indicator_id,period,result,status,created_by) values(i,'Enero,2030',50,'Fuera de meta',u) returning id into r;
 c:=save_cause_analysis(r,'Causa de prueba'); a:=add_corrective_action(c,'Acción de prueba','Descripción');
 t1:=save_corrective_task(a,null,'Primera tarea','Descripción',50); t2:=save_corrective_task(a,null,'Segunda tarea','Descripción',0);
 blocked:=false;
 begin perform notify_corrective_task(t1); exception when others then blocked:=true; end;
 if not blocked then raise exception 'Se notificó sin 100'; end if;
 perform save_corrective_task(a,t1,'Primera tarea','Descripción',100); perform notify_corrective_task(t1);
 if (select review_status from corrective_tasks where id=t2)<>'Borrador' then raise exception 'La notificación afectó otra tarea'; end if;
 blocked:=false;
 begin perform review_corrective_task(t1,true,''); exception when others then blocked:=true; end;
 if not blocked then raise exception 'Gerente aprobó una tarea'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-gcg@example.invalid','role','authenticated')::text,true);
 perform review_corrective_task(t1,false,'Subsanar evidencia');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-manager@example.invalid','role','authenticated')::text,true);
 perform update_corrective_action(a,'Acción corregida','Descripción subsanada');
 perform save_corrective_task(a,t1,'Primera tarea corregida','Subsanada',100); perform notify_corrective_task(t1);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-gcg@example.invalid','role','authenticated')::text,true);
 perform review_corrective_task(t1,true,'');
 if (select approved_at from cause_analyses where id=c) is not null then raise exception 'Se cerró análisis con otra tarea pendiente'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-manager@example.invalid','role','authenticated')::text,true);
 perform save_corrective_task(a,t2,'Segunda tarea','Descripción',100); perform notify_corrective_task(t2);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-gcg@example.invalid','role','authenticated')::text,true);
 perform review_corrective_task(t2,true,'');
 if (select approved_at from cause_analyses where id=c) is null then raise exception 'No comenzó la espera de medición'; end if;
 insert into indicator_reports(indicator_id,period,result,status,created_by,created_at) values(i,'Febrero,2030',95,'En meta',u,now()+interval '1 second') returning id into next_r;
 if (select status from cause_analyses where id=c)<>'Eficaz' then raise exception 'Medición en meta no marcó eficaz'; end if;
 update indicator_reports set result=40 where id=next_r;
 if (select status from cause_analyses where id=c)<>'Pendiente de verificación' then raise exception 'Medición corregida no reevaluó eficacia'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-manager@example.invalid','role','authenticated')::text,true);
 newer:=save_cause_analysis(next_r,'Causa de prueba repetida');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-gcg@example.invalid','role','authenticated')::text,true);
 perform decide_cause_efficacy(c,true,'La causa se repite');
 if (select status from cause_analyses where id=c)<>'No eficaz' then raise exception 'No guardó decisión de causa similar'; end if;
 update indicator_reports set result=96 where id=next_r;
 if (select status from cause_analyses where id=c)<>'No eficaz' then raise exception 'Se sobrescribió decisión manual GCG'; end if;
 update indicator_reports set result=40 where id=next_r;
 update cause_analyses set status='Pendiente de verificación',efficacy_decided_by=null where id=c;
 perform decide_cause_efficacy(c,false,'Se identificó una causa diferente');
 if (select status from cause_analyses where id=c)<>'Eficaz' then raise exception 'Causa diferente no marcó eficaz'; end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-intruder@example.invalid','role','authenticated')::text,true);
 execute 'set local role authenticated';
 if exists(select 1 from cause_analyses where id=c) then raise exception 'Cuenta ajena pudo leer análisis'; end if;
 blocked:=false;
 begin perform save_cause_analysis(r,'No autorizado'); exception when others then blocked:=true; end;
 if not blocked then raise exception 'Cuenta ajena pudo escribir análisis'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'email','corrective-manager@example.invalid','role','authenticated')::text,true);
 execute 'set local role authenticated';
 if not exists(select 1 from cause_analyses where id=c) then raise exception 'Responsable no pudo leer su análisis'; end if;
 execute 'reset role';
 if has_table_privilege('authenticated','public.corrective_tasks','UPDATE') then raise exception 'Escritura directa no protegida'; end if;
 if has_function_privilege('authenticated','public.refresh_analysis_followup(bigint)','EXECUTE') then raise exception 'Función interna expuesta'; end if;
 if has_function_privilege('anon','public.notify_corrective_task(bigint)','EXECUTE') then raise exception 'Función expuesta anónimamente'; end if;
 if not exists(select 1 from storage.buckets where id='corrective-evidence' and not public and file_size_limit=20971520) then raise exception 'Evidencias no privadas'; end if;
 if not exists(select 1 from corrective_events where task_id=t1 and event='Tarea observada') then raise exception 'Falta auditoría'; end if;
end; $$;
select 'OK: notificación individual, observación/subsanación, aprobación, eficacia y permisos' as resultado;
rollback;
