import React from 'react';
import { Calendar, FilePenLine, Target, User } from 'lucide-react';
import { personName } from './lib/personNames';

const executionDate = value => value ? new Intl.DateTimeFormat('es-PE', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(`${value}T12:00:00Z`)) : 'Sin fecha programada';

export default function StrategicActions({ actions, users, canEdit, onEdit }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <header className="flex items-center gap-3 border-b border-slate-100 px-5 py-4"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-700"><Target className="h-5 w-5" /></span><div><h3 className="text-base font-semibold text-slate-900">Acciones estratégicas</h3><p className="mt-0.5 text-xs text-slate-500">Iniciativas para impulsar este objetivo</p></div><span className="ml-auto rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{actions.length} {actions.length === 1 ? 'acción' : 'acciones'}</span></header>
    <div className="grid gap-3 p-4 lg:grid-cols-2">{actions.map((action, index) => <article key={action.id} className="relative flex flex-col overflow-hidden rounded-xl border border-slate-200 bg-white p-4 transition hover:border-blue-200 hover:shadow-md"><span className="absolute inset-y-0 left-0 w-1 bg-blue-500" /><div className="mb-3 flex items-center justify-between gap-3"><span className="text-xs font-semibold tracking-wide text-blue-700">ACCIÓN {String(index + 1).padStart(2, '0')}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-medium text-slate-600">{action.status || 'En progreso'}</span></div><h4 className="text-sm font-semibold leading-6 text-slate-900">{action.name}</h4>{action.description && <p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-slate-500">{action.description}</p>}<div className="mt-auto pt-4"><div className="space-y-2 rounded-lg bg-slate-50 p-3 text-xs text-slate-600"><p className="flex items-center gap-2"><User className="h-4 w-4 shrink-0 text-blue-500" /><span>{personName(action.ownerId, users)}</span></p><p className="flex items-center gap-2"><Calendar className="h-4 w-4 shrink-0 text-blue-500" /><span>Ejecución · {executionDate(action.dueDate)}</span></p></div>{canEdit && <button onClick={() => onEdit(action)} className="mt-3 flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-xs font-semibold text-blue-700 hover:bg-blue-50"><FilePenLine className="h-4 w-4" />Editar acción</button>}</div></article>)}{!actions.length && <p className="col-span-full py-5 text-center text-sm text-slate-500">Aún no hay acciones estratégicas. Crea la primera desde el botón superior.</p>}</div>
  </section>;
}
