-- Bionexora: datos operativos persistentes.
-- Ejecutar una sola vez en Supabase > SQL Editor, después de 001_roles.sql.

create table if not exists public.objectives (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text not null,
  owner_email text,
  progress integer not null default 0 check (progress between 0 and 100),
  status text not null default 'No iniciado',
  created_date date not null default current_date,
  target_date date not null,
  stakeholders jsonb not null default '[]'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  objective_id bigint not null references public.objectives(id) on delete cascade,
  name text not null,
  status text not null default 'En progreso',
  progress integer not null default 0 check (progress between 0 and 100),
  owner_email text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.strategic_actions (
  id bigint generated by default as identity primary key,
  objective_id bigint not null references public.objectives(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  name text not null,
  description text,
  status text not null default 'En progreso',
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.indicators (
  id bigint generated by default as identity primary key,
  objective_id bigint not null references public.objectives(id) on delete cascade,
  name text not null,
  resource text,
  formula text,
  target numeric not null,
  unit text not null,
  comparator text not null check (comparator in ('>', '>=', '=', '<=', '<')),
  frequency text not null check (frequency in ('Mensual', 'Bimestral', 'Trimestral', 'Semestral', 'Anual')),
  owner_email text,
  status text not null default 'Sin reporte',
  approval_status text not null default 'Pendiente de aprobación',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.indicator_reports (
  id bigint generated by default as identity primary key,
  indicator_id bigint not null references public.indicators(id) on delete cascade,
  period text not null,
  result numeric not null,
  status text not null check (status in ('En meta', 'Fuera de meta')),
  registered_date date not null default current_date,
  observations text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists objectives_created_by_idx on public.objectives(created_by);
create index if not exists projects_objective_id_idx on public.projects(objective_id);
create index if not exists strategic_actions_objective_id_idx on public.strategic_actions(objective_id);
create index if not exists indicators_objective_id_idx on public.indicators(objective_id);
create index if not exists indicator_reports_indicator_id_idx on public.indicator_reports(indicator_id);

-- Usuarios autenticados trabajan sobre el mismo portafolio institucional.
-- Las pantallas de Bionexora limitan las acciones disponibles según el rol.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['objectives', 'projects', 'strategic_actions', 'indicators', 'indicator_reports']
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists "Authenticated users manage %s" on public.%I', table_name, table_name);
    execute format(
      'create policy "Authenticated users manage %s" on public.%I for all to authenticated using (true) with check (true)',
      table_name, table_name
    );
  end loop;
end $$;
