-- Bionexora: responsables, vigencia anual y gobierno de indicadores.
-- Ejecutar después de 001_roles.sql y 002_operational_data.sql.

alter table public.objectives alter column category drop not null;
alter table public.objectives add column if not exists validity_start_year integer;
alter table public.objectives add column if not exists validity_end_year integer;
alter table public.objectives drop constraint if exists objectives_validity_years_check;
alter table public.objectives add constraint objectives_validity_years_check
  check (validity_start_year is null or validity_end_year is null or validity_end_year >= validity_start_year);

alter table public.strategic_actions add column if not exists owner_email text;
alter table public.indicators add column if not exists review_frequency text;
alter table public.indicators drop constraint if exists indicators_review_frequency_check;
alter table public.indicators add constraint indicators_review_frequency_check
  check (review_frequency is null or review_frequency in ('Mensual', 'Bimestral', 'Trimestral', 'Semestral', 'Anual'));

create table if not exists public.indicator_target_history (
  id bigint generated by default as identity primary key,
  indicator_id bigint not null references public.indicators(id) on delete cascade,
  target numeric not null,
  comparator text not null check (comparator in ('>', '>=', '=', '<=', '<')),
  effective_date date not null default current_date,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists indicator_target_history_indicator_id_idx on public.indicator_target_history(indicator_id, effective_date);

alter table public.indicator_target_history enable row level security;
drop policy if exists "Authenticated users manage indicator target history" on public.indicator_target_history;
create policy "Authenticated users manage indicator target history"
  on public.indicator_target_history for all to authenticated using (true) with check (true);

-- Las listas de responsables e interesados se construyen desde los usuarios ya autenticados.
drop policy if exists "Users can read their own profile" on public.profiles;
drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
  on public.profiles for select to authenticated using (true);
